amcl:
  ros__parameters:

    use_sim_time: true

    # ==== Параметры фильтра частиц ====
    alpha1_rot_rot: 0.05     # шум вращения при вращении
    alpha2_rot_tr: 0.01      # шум вращения при движении вперёд
    alpha3_tr_tr: 0.05       # шум движения при движении
    alpha4_tr_rot: 0.01      # шум движения при вращении
    alpha_slow: 0.01         # скорость обновления среднего веса частиц
    alpha_fast: 0.99         # скорость обновления наиболее вероятного положения

    base_frame_id: "base_link"          # система координат робота
    global_frame_id: "map"             # глобальная система координат (карта)
    odom_frame_id: "odom"              # система координат одометрии

    # ==== Настройки LiDAR ====
    laser_scanner_topic: "/scan"       # топик с данными сканирования
    laser_max_beams: 60                # максимальное количество лучей, используемых из скана
    laser_max_range: 30.0              # максимальная дистанция для лучей (в метрах)

    # ==== Параметры частиц ====
    min_particles: 500                 # минимальное количество частиц
    max_particles: 2000                # максимальное количество частиц
    initial_pose_x: 0.0                # начальная позиция x (если не задана через /initialpose)
    initial_pose_y: 0.0                # начальная позиция y
    initial_pose_a: 0.0                # начальный угол ориентации (радианы)

    # ==== Другие параметры ====
    gui_publish_rate: 50.0             # частота публикации частиц для отладки
    tf_broadcast: true                 # публиковать ли TF transform map -> odom
    resample_interval: 1               # интервал пересчёта частиц (каждый N-й раз)
    transform_tolerance: 0.1           # допуск времени между сообщениями TF
    update_min_d: 0.2                  # мин. расстояние для обновления позиции
    update_min_a: 0.5                  # мин. угол поворота для обновления позиции

    # ==== Вероятностные модели ====
    z_hit: 0.95                        # вероятность совпадения луча с картой
    z_short: 0.1                       # вероятность коротких показаний
    z_max: 0.05                        # вероятность max значения (бесконечности)
    z_rand: 0.05                       # вероятность случайных значений
    sigma_hit: 0.2                     # стандартное отклонение для совпадения
    lambda_short: 0.1                  # экспоненциальное затухание для short
    gaussian_sigma: 0.01              # для вычисления вероятности совпадения
    pf_err: 0.05                      # точность алгоритма частиц
    pf_z: 0.99                        # порог уверенности

    # ==== Тип модели движения ====
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
